### PR TITLE
rolling back making Client private

### LINKED ISSUE #24: Client is now package private
See my comment on fefa97b88fd
```
[error] /Users/brandon/Documents/workspace/schoox-api-scalawrapper/src/main/scala/com/schoox/api/Api.scala:36: class Client in package featherbed cannot be accessed in package featherbed
[error]   private val client = new featherbed.Client(baseUrl)
```

### PR DESCRIPTION
**Pull request by bhudgeons**
fixes #24

### CODE REVIEW

**Comment by ilya-murzinov** [comment]
My bad!
I thought that it's the same, but it obviously is not.

So what is the meaning of ```private[featherbed]``` here at all?

And also, should not [this](https://github.com/finagle/featherbed/commit/fefa97b88fd1c0241c8fec431838d6ed9eec3e5e#diff-137663d6fe0586248e87fae8a61371d7R312) be reverted? And other places..

**Comment by ilya-murzinov** [comment]
Oh, I get it. It's the primary constructor access modifier.
Sorry!

@bhudgeons do you mind also reverting other places I screwed up?

**Comment by bhudgeons** [comment]
I'm not sure we need to. AFAIK, we don't use the constructors of PostRequest etc outside of featherbed internals. Let me see if I can identify any other problem areas.

**Comment by bhudgeons** [comment]
So ... my project (basic API client using featherbed) compiles fine with just the one-line change here. So I guess the question is more for @jeremyrsmith : Do you want PostRequest etc to be part of the API, or keep them private?

**Comment by jeremyrsmith** [comment]
Closing this as it's obviated by https://github.com/finagle/featherbed/pull/29

**Pull request closed without merging**
