### PR TITLE
Update scala and dependencies versions

### PR DESCRIPTION
**Pull request by ilya-murzinov**

### CODE REVIEW

**Comment by ilya-murzinov** [comment]
@jeremyrsmith please take a look

**Comment by ilya-murzinov** [comment]
No, too soon...
Tut works 2.11 with well, but hangs with 2.12.
```
val result = ...
Await.result(result)
```
works, but
```Await.result {...}```
hangs.
Very strange.

**Comment by ilya-murzinov** [comment]
Finally works!

**Comment by jeremyrsmith** [comment]
Thanks @ilya-murzinov!

**Pull request merged**
