### PR TITLE
[#20] Improved query string implementation

### LINKED ISSUE #20: Improve query string implementation
See #16 for reference
> I would rather have the query string itself be agnostic to its content (rather than locking it into "foo=bar&baz=buzz" for example). Also, I don't think you can necessarily treat params in that fashion as a Map, because a particular key may occur more than once, which Map doesn't allow.

### PR DESCRIPTION
**Pull request by ilya-murzinov**
Resolves #20

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
👍  LGTM

**Comment by bhudgeons** [comment]
Just a thought ... instead of (or in addition to) accepting varargs of (String,String), we might want to use List[String,String] or (I prefer) Map[String,String]. 
```
[error] /Users/brandon/Documents/workspace/schoox-api-scalawrapper/src/main/scala/com/schoox/api/Api.scala:158: applyDynamic does not support passing a vararg parameter
[error]       .accept[Coproduct.`"application/json"`.T]
```

**Comment by ilya-murzinov** [comment]
@bhudgeons do you mind sharing the code which leads to this error? May be open a new issue for this?

**Comment by bhudgeons** [comment]
Whoops ... this might not be caused by that varargs. I'm getting it with this:

```
[error] /Users/brandon/Documents/workspace/schoox-api-scalawrapper/src/main/scala/com/schoox/api/Api.scala:47: applyDynamic does not support passing a vararg parameter
[error]   type JSON = Coproduct.`"application/json"`.T
[error]                         ^
```

**Comment by bhudgeons** [comment]
Or maybe it is ... https://issues.scala-lang.org/browse/SI-7420

**Pull request merged**
